### PR TITLE
Episode 29

### PR DESCRIPTION
**Pull request by sockeqwe**
@arturdryomov Can you please publish this on our website? I didn't get the scripts to run (could you also add a README how to do it) 

This PR contains the Episode 29 markdown file.  (Also updated an older episode with Ash Davies type / added twitter handle)

### CODE REVIEW

**Comment by arturdryomov** [comment]
@sockeqwe, I think scripts are in the repo. Merge this PR, then run `bash scripts/publish.sh`. It should push new things to the `gh-pages` branch.

**Review by arturdryomov — APPROVED** [review]

**Comment by sockeqwe** [comment]
Yea,I tried this, I have some issues with hugo executables on my machine
... Will give it another try later.

Artur Dryomov <notifications@github.com> schrieb am Sa., 28. Dez. 2019,
14:32:

**Comment by arturdryomov** [comment]
@sockeqwe, huh, it pushed all right but broke the site. Welp. Had to tweak a bunch of things, but it is up and running now (including the new episode).

**Comment by sockeqwe** [comment]
Thanks

Artur Dryomov <notifications@github.com> schrieb am Sa., 28. Dez. 2019,
15:04:

**Pull request merged**
